[env]
TERM = "xterm-256color"
ALACRITTY = "true"

[terminal.shell]
program = "/opt/homebrew/bin/fish"
args = ["--login"]

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

opacity = 0.8
blur = true

# option_as_alt = "Both"

[mouse]
hide_when_typing = true

[font]
normal.family = "Liga SFMono Nerd Font"

size=18

[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left",  mods = "Alt", chars = "\u001BB" },
]

[general]
import = ["~/.config/alacritty/active-theme.toml"]
